import Head from "next/head";
import { useState } from "react";
import Script from "next/script";
import Navbar from "../components/Navbar"
import styles from "../styles/Home.module.css";
import Content from "../components/Content"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Footer from "../components/Footer";



export default function Home() {

  return (
    <div className="overflow-visible">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        ></link>
        <link
  rel="stylesheet"
  type="text/css"
 
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>
        
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></Script>
    
        <div className="flex ">
      <Navbar />
      <Content  />
        </div>
      
     
  <div className=" absolute top-[315vh]"> 
      <Footer/>
      </div>
      </div>

     
    
    
  );
}
